services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - doc
      - game
      - music
      - picture
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  doc:
    build:
      context: .
      dockerfile: Dockerfile.doc
    command: ["npx", "http-server", "-p", "4000", "doc"]
    ports:
      - "4000:4000"
    tty: true

  game:
    build:
      context: .
      dockerfile: Dockerfile.game
    command: ["npx", "http-server", "-p", "4001", "game/docs"]
    ports:
      - "4001:4001"
    tty: true

  music:
    build:
      context: .
      dockerfile: Dockerfile.music
    command: ["npx", "http-server", "-p", "4002", "music"]
    ports:
      - "4002:4002"
    tty: true

  picture:
    build:
      context: .
      dockerfile: Dockerfile.picture
    command: ["npx", "http-server", "-p", "4003", "picture"]
    ports:
      - "4003:4003"
    tty: true

volumes:
  node_modules: {}
